version: '3.8'

services:
  traffic-classifier:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - ./static/uploads:/app/static/uploads
      - ./image_history.json:/app/image_history.json
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 